version: "3"
services:
  # server:
  #   environment:
  #     DRONE_GITHUB_CLIENT_ID: 
  #     DRONE_GITHUB_CLIENT_SECRET: 
  #     DRONE_RPC_SECRET: 
  #     DRONE_SERVER_HOST: 192.168.68.100
  #     DRONE_SERVER_PROTO: http
  #   image: drone/drone:2
  #   container_name: server
  #   ports:
  #     - "80:80"
  # WARNING: If you have an OSX (Mac OS) host and a Linux container https://stackoverflow.com/questions/32163955/how-to-run-shell-script-on-host-from-docker-container
  # osxrunner:
  #   image: alpine
  #   container_name: osxrunner-pipe
  #   command: |
  #     /bin/sh -c "echo \"hey there\" > runnerpipe && while sleep 1000; do :; done"
  #     # /bin/sh -c "echo \"tmux new -d './drone-runner-aws-darwin-amd64 delegate --envfile=.env --pool=pool.yml |& tee /tmp/runner.log'\" > runnerpipe && while sleep 1000; do :; done"
  #   working_dir: /workspace
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ../contrib/runner/:/workspace:cached
  #   depends_on:
  #     - server
  harness_aws:
    # environment:
      # VAULT_ADDR: http://vault:8200
      # VAULT_TOKEN: root
    build:
      context: ../contrib/docker
      dockerfile: dev.Dockerfile
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../:/workspace:cached
      - ~/.kube:/workspace/.kube:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    container_name: harness_aws
